[2023-11-14T11:50:27.650+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: plugin_dag.mysql_to_postgres manual__2023-11-14T06:20:20.337800+00:00 [queued]>
[2023-11-14T11:50:27.657+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: plugin_dag.mysql_to_postgres manual__2023-11-14T06:20:20.337800+00:00 [queued]>
[2023-11-14T11:50:27.657+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-14T11:50:27.667+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): mysql_to_postgres> on 2023-11-14 06:20:20.337800+00:00
[2023-11-14T11:50:27.671+0530] {standard_task_runner.py:57} INFO - Started process 18121 to run task
[2023-11-14T11:50:27.673+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'plugin_dag', 'mysql_to_postgres', 'manual__2023-11-14T06:20:20.337800+00:00', '--job-id', '4600', '--raw', '--subdir', 'DAGS_FOLDER/dag_plugins.py', '--cfg-path', '/tmp/tmp8cbuse8p']
[2023-11-14T11:50:27.674+0530] {standard_task_runner.py:85} INFO - Job 4600: Subtask mysql_to_postgres
[2023-11-14T11:50:27.696+0530] {task_command.py:415} INFO - Running <TaskInstance: plugin_dag.mysql_to_postgres manual__2023-11-14T06:20:20.337800+00:00 [running]> on host harika-Latitude-5511
[2023-11-14T11:50:27.828+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='plugin_dag' AIRFLOW_CTX_TASK_ID='mysql_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T06:20:20.337800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-14T06:20:20.337800+00:00'
[2023-11-14T11:50:27.829+0530] {logging_mixin.py:151} INFO - #custom hook
[2023-11-14T11:50:27.829+0530] {logging_mixin.py:151} INFO - fetching records from MYSQL table
[2023-11-14T11:50:27.829+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/harika/airflow/dags/dag_plugins.py", line 10, in trigger_hook
    MySQLToPostgresHook().copy_table('mysql_conn', 'postgrs_conn')
  File "/home/harika/airflow/plugins/demo_plugin.py", line 74, in copy_table
    mysqlserver = MySQLToPostgresHook(mysql_conn_id)
TypeError: MySQLToPostgresHook.__init__() takes 1 positional argument but 2 were given
[2023-11-14T11:50:27.831+0530] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=plugin_dag, task_id=mysql_to_postgres, execution_date=20231114T062020, start_date=20231114T062027, end_date=20231114T062027
[2023-11-14T11:50:27.838+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 4600 for task mysql_to_postgres (MySQLToPostgresHook.__init__() takes 1 positional argument but 2 were given; 18121)
[2023-11-14T11:50:27.845+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-14T11:50:27.853+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
