[2023-11-06T10:24:21.081+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hooks_demo.transfer scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-06T10:24:21.087+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hooks_demo.transfer scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-06T10:24:21.088+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-06T10:24:21.101+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transfer> on 2023-11-03 00:00:00+00:00
[2023-11-06T10:24:21.106+0530] {standard_task_runner.py:57} INFO - Started process 6903 to run task
[2023-11-06T10:24:21.108+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'hooks_demo', 'transfer', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '4255', '--raw', '--subdir', 'DAGS_FOLDER/hooks.py', '--cfg-path', '/tmp/tmpyzcpkr_1']
[2023-11-06T10:24:21.109+0530] {standard_task_runner.py:85} INFO - Job 4255: Subtask transfer
[2023-11-06T10:24:21.143+0530] {task_command.py:415} INFO - Running <TaskInstance: hooks_demo.transfer scheduled__2023-11-03T00:00:00+00:00 [running]> on host harika-Latitude-5511
[2023-11-06T10:24:21.284+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='hooks_demo' AIRFLOW_CTX_TASK_ID='transfer' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-06T10:24:21.288+0530] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-06T10:24:21.307+0530] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-06T10:24:21.321+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/harika/airflow/dags/hooks.py", line 28, in transfer_function
    source_cursor.execute(query)
psycopg2.errors.UndefinedTable: relation "source_city_table" does not exist
LINE 1: select * from source_city_table
                      ^

[2023-11-06T10:24:21.324+0530] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=hooks_demo, task_id=transfer, execution_date=20231103T000000, start_date=20231106T045421, end_date=20231106T045421
[2023-11-06T10:24:21.332+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 4255 for task transfer (relation "source_city_table" does not exist
LINE 1: select * from source_city_table
                      ^
; 6903)
[2023-11-06T10:24:21.360+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T10:24:21.371+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-16T16:06:37.620+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hooks_demo.transfer scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-16T16:06:37.625+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hooks_demo.transfer scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-16T16:06:37.625+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-16T16:06:37.635+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transfer> on 2023-11-03 00:00:00+00:00
[2023-11-16T16:06:37.639+0530] {standard_task_runner.py:57} INFO - Started process 146628 to run task
[2023-11-16T16:06:37.641+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'hooks_demo', 'transfer', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '4714', '--raw', '--subdir', 'DAGS_FOLDER/hooks_demo.py', '--cfg-path', '/tmp/tmp4fgw7j9x']
[2023-11-16T16:06:37.642+0530] {standard_task_runner.py:85} INFO - Job 4714: Subtask transfer
[2023-11-16T16:06:37.666+0530] {task_command.py:415} INFO - Running <TaskInstance: hooks_demo.transfer scheduled__2023-11-03T00:00:00+00:00 [running]> on host harika-Latitude-5511
[2023-11-16T16:06:37.799+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='hooks_demo' AIRFLOW_CTX_TASK_ID='transfer' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-16T16:06:37.803+0530] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-16T16:06:37.815+0530] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-16T16:06:37.825+0530] {logging_mixin.py:151} INFO - records [('New york                                          ', 'ny                  ')]
[2023-11-16T16:06:37.827+0530] {logging_mixin.py:151} INFO - Data transferred successfully
[2023-11-16T16:06:37.827+0530] {python.py:194} INFO - Done. Returned value was: None
[2023-11-16T16:06:37.831+0530] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=hooks_demo, task_id=transfer, execution_date=20231103T000000, start_date=20231116T103637, end_date=20231116T103637
[2023-11-16T16:06:37.853+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-16T16:06:37.863+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
