[2023-10-25T18:08:12.684+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_dag.send_notification_email manual__2023-10-25T12:38:04.668425+00:00 [queued]>
[2023-10-25T18:08:12.690+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_dag.send_notification_email manual__2023-10-25T12:38:04.668425+00:00 [queued]>
[2023-10-25T18:08:12.691+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-25T18:08:12.703+0530] {taskinstance.py:1380} INFO - Executing <Task(EmailOperator): send_notification_email> on 2023-10-25 12:38:04.668425+00:00
[2023-10-25T18:08:12.706+0530] {standard_task_runner.py:57} INFO - Started process 91880 to run task
[2023-10-25T18:08:12.709+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'wikipedia_dag', 'send_notification_email', 'manual__2023-10-25T12:38:04.668425+00:00', '--job-id', '1577', '--raw', '--subdir', 'DAGS_FOLDER/word_count.py', '--cfg-path', '/tmp/tmpxrfr08jw']
[2023-10-25T18:08:12.709+0530] {standard_task_runner.py:85} INFO - Job 1577: Subtask send_notification_email
[2023-10-25T18:08:12.734+0530] {task_command.py:415} INFO - Running <TaskInstance: wikipedia_dag.send_notification_email manual__2023-10-25T12:38:04.668425+00:00 [running]> on host harika-Latitude-5511
[2023-10-25T18:08:12.777+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='harikasree2225@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='wikipedia_dag' AIRFLOW_CTX_TASK_ID='send_notification_email' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T12:38:04.668425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-25T12:38:04.668425+00:00'
[2023-10-25T18:08:12.785+0530] {logging_mixin.py:151} WARNING - /home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-25T18:08:12.786+0530] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-25T18:09:12.867+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: timed out
[2023-10-25T18:09:12.879+0530] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=wikipedia_dag, task_id=send_notification_email, execution_date=20231025T123804, start_date=20231025T123812, end_date=20231025T123912
[2023-10-25T18:09:12.906+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 1577 for task send_notification_email (timed out; 91880)
[2023-10-25T18:09:12.932+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-25T18:09:12.946+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
